### PR TITLE
Get year options from data

### LINKED ISSUE #12: Pull year info from returned data
Currently, the year-dropdown displays 2011 (when Letterboxd was created) to [current year]. As I believe you can log movies at any date, we should probably just pull the available year choices from the data returned from the API, i.e: [earliest year they've logged something] – [current year] .

### PR DESCRIPTION
**Pull request by qjack001**
Closes #12.

### CODE REVIEW

**Review by HoloPollock — COMMENTED** [review]
Why a function and not just return the Val as a ref in the setup because you can return values in setup and have it be accsesisble to the template

**Comment by HoloPollock** [comment]
https://v3.vuejs.org/guide/composition-api-setup.html#usage-with-templates

**Review by HoloPollock — APPROVED** [review]
Sorry I can't read lol

**Comment by qjack001** [comment]
> Why a function and not just return the Val as a ref in the setup because you can return values in setup and have it be accsesisble to the template

Ya I couldn't get the emit working (in retrospect, perhaps a problem with webpack and not the way I was doing it)

**Comment by qjack001** [comment]
feel free to refactor tho if you think it'll be cleaner

**Comment by HoloPollock** [comment]
No I think you did it right like it seems like you just don't need to return thing in script setup to expose to template but you did what I would do

**Comment by HoloPollock** [comment]
I just read wrong that you mates lowest year type function

**Comment by HoloPollock** [comment]
Yah like the only thing I would have done is use a watch to re run the API on change and just have the text box change username rather than call the API but I don't think it's that important

**Pull request merged**
